CREATE TABLE [dbo].[Event](
	[GameId] [varchar](12) NOT NULL,
	[AwayTeamId] [varchar](3) NULL,
	[Inning] [int] NULL,
	[BattingTeam] [varchar](1) NULL,
	[Outs] [int] NULL,
	[Balls] [int] NULL,
	[Strikes] [int] NULL,
	[PitchSequence] [varchar](max) NULL,
	[AwayScore] [int] NULL,
	[HomeScore] [int] NULL,
	[BatterId] [varchar](8) NULL,
	[BatterHand] [varchar](1) NULL,
	[ResultBatterId] [varchar](8) NULL,
	[ResultBatterHand] [varchar](1) NULL,
	[PitcherId] [varchar](8) NULL,
	[PitcherHand] [varchar](1) NULL,
	[ResultPitcherId] [varchar](8) NULL,
	[ResultPitcherHand] [varchar](1) NULL,
	[Catcher] [varchar](8) NULL,
	[FirstBaseman] [varchar](8) NULL,
	[SecondBaseman] [varchar](8) NULL,
	[ThirdBaseman] [varchar](8) NULL,
	[Shortstop] [varchar](8) NULL,
	[LeftFielder] [varchar](8) NULL,
	[CenterFielder] [varchar](8) NULL,
	[RightFielder] [varchar](8) NULL,
	[Runner1Id] [varchar](8) NULL,
	[Runner2Id] [varchar](8) NULL,
	[Runner3Id] [varchar](8) NULL,
	[EventText] [varchar](50) NULL,
	[LeadOffFlag] [varchar](50) NULL,
	[PinchHitFlag] [varchar](50) NULL,
	[DefensivePosition] [int] NULL,
	[LineupPosition] [int] NULL,
	[EventType] [int] NULL,
	[BatterEventFlag] [varchar](50) NULL,
	[OfficialTimeAtBatFlag] [varchar](50) NULL,
	[HitValue] [int] NULL,
	[SacrificeHitFlag] [varchar](50) NULL,
	[SacrificeFlyFlag] [varchar](50) NULL,
	[OutOnPlay] [int] NULL,
	[DoublePlayFlag] [varchar](50) NULL,
	[TriplePlayFlag] [varchar](50) NULL,
	[RbiOnPlay] [int] NULL,
	[WildPitchFlag] [varchar](50) NULL,
	[PassedBallFlag] [varchar](50) NULL,
	[FieldedBy] [int] NULL,
	[BattedBallType] [varchar](1) NULL,
	[BuntFlag] [varchar](50) NULL,
	[FoulFlag] [varchar](50) NULL,
	[HitLocation] [varchar](50) NULL,
	[NumberOfErrors] [int] NULL,
	[FirstErrorPlayer] [int] NULL,
	[FirstErrorType] [varchar](50) NULL,
	[SecondErrorPlayer] [int] NULL,
	[SecondErrorType] [varchar](50) NULL,
	[ThirdErrorPlayer] [int] NULL,
	[ThirdErrorType] [varchar](50) NULL,
	[BatterDestination] [int] NULL,
	[Runner1Destination] [int] NULL,
	[Runner2Destination] [int] NULL,
	[Runner3Destination] [int] NULL,
	[PlayOnBatter] [varchar](max) NULL,
	[PlayOnRunner1] [varchar](max) NULL,
	[PlayOnRunner2] [varchar](max) NULL,
	[PlayOnRunner3] [varchar](max) NULL,
	[Runner1StolenBaseFlag] [varchar](50) NULL,
	[Runner2StolenBaseFlag] [varchar](50) NULL,
	[Runner3StolenBaseFlag] [varchar](50) NULL,
	[Runner1CaughtStealingFlag] [varchar](50) NULL,
	[Runner2CaughtStealingFlag] [varchar](50) NULL,
	[Runner3CaughtStealingFlag] [varchar](50) NULL,
	[Runner1PickOffFlag] [varchar](50) NULL,
	[Runner2PickOffFlag] [varchar](50) NULL,
	[Runner3PickOffFlag] [varchar](50) NULL,
	[PitcherChargedWithRunner1] [varchar](8) NULL,
	[PitcherChargedWithRunner2] [varchar](8) NULL,
	[PitcherChargedWithRunner3] [varchar](8) NULL,
	[NewGameFlag] [varchar](50) NULL,
	[EndGameFlag] [varchar](50) NULL,
	[PinchRunner1Flag] [varchar](50) NULL,
	[PinchRunner2Flag] [varchar](50) NULL,
	[PinchRunner3Flag] [varchar](50) NULL,
	[RunnerRemovedForPinchRunner1] [varchar](8) NULL,
	[RunnerRemovedForPinchRunner2] [varchar](8) NULL,
	[RunnerRemovedForPinchRunner3] [varchar](8) NULL,
	[BatterRemovedForPinchHitter] [varchar](8) NULL,
	[PositionOfBatterRemovedForPinchHitter] [int] NULL,
	[FielderWithFirstPutout] [int] NULL,
	[FielderWithSecondPutout] [int] NULL,
	[FielderWithThirdPutout] [int] NULL,
	[Assist1Fielder] [int] NULL,
	[Assist2Fielder] [int] NULL,
	[Assist3Fielder] [int] NULL,
	[Assist4Fielder] [int] NULL,
	[Assist5Fielder] [int] NULL,
	[EventNumber] [int] NOT NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[GameId] ASC,
	[EventNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


