USE [mlb]
GO

/****** Object:  Table [dbo].[GameExt]    Script Date: 11/29/2017 9:47:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GameExt](
	[GAME_ID] [nvarchar](50) NULL,
	[DATE] [nvarchar](50) NULL,
	[GAME_NUMBER] [nvarchar](50) NULL,
	[AWAY_TEAM_LEAGUE_ID] [nvarchar](50) NULL,
	[HOME_TEAM_LEAGUE_ID] [nvarchar](50) NULL,
	[AWAY_TEAM_GAME_CT] [nvarchar](50) NULL,
	[HOME_TEAM_GAME_CT] [nvarchar](50) NULL,
	[OUTS_CT] [nvarchar](50) NULL,
	[COMPLETION_TX] [nvarchar](50) NULL,
	[FORFEIT_TX] [nvarchar](50) NULL,
	[PROTEST_TX] [nvarchar](50) NULL,
	[AWAY_LINE_TX] [nvarchar](50) NULL,
	[HOME_LINE_TX] [nvarchar](50) NULL,
	[AWAY_AB_CT] [nvarchar](50) NULL,
	[AWAY_2B_CT] [nvarchar](50) NULL,
	[AWAY_3B_CT] [nvarchar](50) NULL,
	[AWAY_HR_CT] [nvarchar](50) NULL,
	[AWAY_BI_CT] [nvarchar](50) NULL,
	[AWAY_SH_CT] [nvarchar](50) NULL,
	[AWAY_SF_CT] [nvarchar](50) NULL,
	[AWAY_HP_CT] [nvarchar](50) NULL,
	[AWAY_BB_CT] [nvarchar](50) NULL,
	[AWAY_IBB_CT] [nvarchar](50) NULL,
	[AWAY_SO_CT] [nvarchar](50) NULL,
	[AWAY_SB_CT] [nvarchar](50) NULL,
	[AWAY_CS_CT] [nvarchar](50) NULL,
	[AWAY_GDP_CT] [nvarchar](50) NULL,
	[AWAY_XI_CT] [nvarchar](50) NULL,
	[AWAY_PITCHER_CT] [nvarchar](50) NULL,
	[AWAY_ER_CT] [nvarchar](50) NULL,
	[AWAY_TER_CT] [nvarchar](50) NULL,
	[AWAY_WP_CT] [nvarchar](50) NULL,
	[AWAY_BK_CT] [nvarchar](50) NULL,
	[AWAY_PO_CT] [nvarchar](50) NULL,
	[AWAY_A_CT] [nvarchar](50) NULL,
	[AWAY_PB_CT] [nvarchar](50) NULL,
	[AWAY_DP_CT] [nvarchar](50) NULL,
	[AWAY_TP_CT] [nvarchar](50) NULL,
	[HOME_AB_CT] [nvarchar](50) NULL,
	[HOME_2B_CT] [nvarchar](50) NULL,
	[HOME_3B_CT] [nvarchar](50) NULL,
	[HOME_HR_CT] [nvarchar](50) NULL,
	[HOME_RBI_CT] [nvarchar](50) NULL,
	[HOME_SH_CT] [nvarchar](50) NULL,
	[HOME_SF_CT] [nvarchar](50) NULL,
	[HOME_HP_CT] [nvarchar](50) NULL,
	[HOME_BB_CT] [nvarchar](50) NULL,
	[HOME_IBB_CT] [nvarchar](50) NULL,
	[HOME_SO_CT] [nvarchar](50) NULL,
	[HOME_SB_CT] [nvarchar](50) NULL,
	[HOME_CS_CT] [nvarchar](50) NULL,
	[HOME_GDP_CT] [nvarchar](50) NULL,
	[HOME_XI_CT] [nvarchar](50) NULL,
	[HOME_PITCHER_CT] [nvarchar](50) NULL,
	[HOME_ER_CT] [nvarchar](50) NULL,
	[HOME_TER_CT] [nvarchar](50) NULL,
	[HOME_WP_CT] [nvarchar](50) NULL,
	[HOME_BK_CT] [nvarchar](50) NULL,
	[HOME_PO_CT] [nvarchar](50) NULL,
	[HOME_A_CT] [nvarchar](50) NULL,
	[HOME_PB_CT] [nvarchar](50) NULL,
	[HOME_DP_CT] [nvarchar](50) NULL,
	[HOME_TP_CT] [nvarchar](50) NULL,
	[UMP_HOME_NAME_TX] [nvarchar](50) NULL,
	[UMP_1B_NAME_TX] [nvarchar](50) NULL,
	[UMP_2B_NAME_TX] [nvarchar](50) NULL,
	[UMP_3B_NAME_TX] [nvarchar](50) NULL,
	[UMP_LF_NAME_TX] [nvarchar](50) NULL,
	[UMP_RF_NAME_TX] [nvarchar](50) NULL,
	[AWAY_MANAGER_ID] [nvarchar](50) NULL,
	[AWAY_MANAGER_NAME_TX] [nvarchar](50) NULL,
	[HOME_MANAGER_ID] [nvarchar](50) NULL,
	[HOME_MANAGER_NAME_TX] [nvarchar](50) NULL,
	[WIN_PIT_NAME_TX] [nvarchar](50) NULL,
	[LOSE_PIT_NAME_TX] [nvarchar](50) NULL,
	[SAVE_PIT_NAME_TX] [nvarchar](50) NULL,
	[GOAHEAD_RBI_ID] [nvarchar](50) NULL,
	[GOAHEAD_RBI_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP1_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP2_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP3_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP4_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP5_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP6_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP7_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP8_BAT_NAME_TX] [nvarchar](50) NULL,
	[AWAY_LINEUP9_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP1_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP2_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP3_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP4_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP5_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP6_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP7_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP8_BAT_NAME_TX] [nvarchar](50) NULL,
	[HOME_LINEUP9_BAT_NAME_TX] [nvarchar](50) NULL,
	[ADD_INFO_TX] [nvarchar](max) NULL,
	[ACQ_INFO_TX] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

