USE [mlb]
GO

/****** Object:  Table [dbo].[Game]    Script Date: 11/24/2017 8:38:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Game](
	[GameId] [nvarchar](50) NULL,
	[Date] [nvarchar](50) NULL,
	[GameNumber] [nvarchar](50) NULL,
	[DayOfTheWeek] [nvarchar](50) NULL,
	[StartTime] [nvarchar](50) NULL,
	[DesignerHitterFlag] [nvarchar](50) NULL,
	[DayNightFlag] [nvarchar](50) NULL,
	[AwayTeamId] [nvarchar](50) NULL,
	[HomeTeamId] [nvarchar](50) NULL,
	[ParkId] [nvarchar](50) NULL,
	[AwayStartPitcherId] [nvarchar](50) NULL,
	[HomeStartPitcherId] [nvarchar](50) NULL,
	[HomePlateUmpireId] [nvarchar](50) NULL,
	[Base1UmpireId] [nvarchar](50) NULL,
	[Base2UmpireId] [nvarchar](50) NULL,
	[Base3UmpireId] [nvarchar](50) NULL,
	[LeftFieldUpireId] [nvarchar](50) NULL,
	[RightFieldUmpireId] [nvarchar](50) NULL,
	[Attendance] [nvarchar](50) NULL,
	[ScorerRecordId] [nvarchar](50) NULL,
	[TranslatorRecordId] [nvarchar](50) NULL,
	[Inputter] [nvarchar](50) NULL,
	[InputTime] [nvarchar](50) NULL,
	[Edit Time] [nvarchar](50) NULL,
	[HowScored] [nvarchar](50) NULL,
	[PitchesEntered] [nvarchar](50) NULL,
	[Temperature] [nvarchar](50) NULL,
	[WindDirection] [nvarchar](50) NULL,
	[WindSpeed] [nvarchar](50) NULL,
	[FieldCondition] [nvarchar](50) NULL,
	[Precipitation] [nvarchar](50) NULL,
	[Sky] [nvarchar](50) NULL,
	[Minutes] [nvarchar](50) NULL,
	[NumberOfInnings] [nvarchar](50) NULL,
	[AwayFinalScore] [nvarchar](50) NULL,
	[HomeFinalScore] [nvarchar](50) NULL,
	[AwayHits] [nvarchar](50) NULL,
	[HomeHits] [nvarchar](50) NULL,
	[AwayErrors] [nvarchar](50) NULL,
	[HomeErrors] [nvarchar](50) NULL,
	[AwayLeftOnBases] [nvarchar](50) NULL,
	[HomeLeftOnBases] [nvarchar](50) NULL,
	[WinningPitcher] [nvarchar](50) NULL,
	[LosingPitcher] [nvarchar](50) NULL,
	[SavePitcher] [nvarchar](50) NULL,
	[GameWinningRbi] [nvarchar](50) NULL,
	[AwayBatter1] [nvarchar](50) NULL,
	[AwayBatter1FieldPosition] [nvarchar](50) NULL,
	[AwayBatter2] [nvarchar](50) NULL,
	[AwayBatter2FieldPosition] [nvarchar](50) NULL,
	[AwayBatter3] [nvarchar](50) NULL,
	[AwayBatter3FieldPosition] [nvarchar](50) NULL,
	[AwayBatter4] [nvarchar](50) NULL,
	[AwayBatter4FieldPosition] [nvarchar](50) NULL,
	[AwayBatter5] [nvarchar](50) NULL,
	[AwayBatter5FieldPosition] [nvarchar](50) NULL,
	[AwayBatter6] [nvarchar](50) NULL,
	[AwayBatter6FieldPosition] [nvarchar](50) NULL,
	[AwayBatter7] [nvarchar](50) NULL,
	[AwayBatterFieldPosition] [nvarchar](50) NULL,
	[AwayBatter8] [nvarchar](50) NULL,
	[AwayBatter8FieldPosition] [nvarchar](50) NULL,
	[AwayBatter9] [nvarchar](50) NULL,
	[AwayBatter9FieldPosition] [nvarchar](50) NULL,
	[HomeBatter1] [nvarchar](50) NULL,
	[HomeBatter1FieldPosition] [nvarchar](50) NULL,
	[HomeBatter2] [nvarchar](50) NULL,
	[HomeBatter2FieldPosition] [nvarchar](50) NULL,
	[HomeBatter3] [nvarchar](50) NULL,
	[HomeBatter3FieldPosition] [nvarchar](50) NULL,
	[HomeBatter4] [nvarchar](50) NULL,
	[HomeBatter4FieldPosition] [nvarchar](50) NULL,
	[HomeBatter5] [nvarchar](50) NULL,
	[HomeBatter5FieldPosition] [nvarchar](50) NULL,
	[HomeBatter6] [nvarchar](50) NULL,
	[HomeBatter6FieldPosition] [nvarchar](50) NULL,
	[HomeBatter7] [nvarchar](50) NULL,
	[HomeBatter7FieldPosition] [nvarchar](50) NULL,
	[HomeBatter8] [nvarchar](50) NULL,
	[HomeBatter8FieldPosition] [nvarchar](50) NULL,
	[HomeBatter9] [nvarchar](50) NULL,
	[HomeBatter9FieldPosition] [nvarchar](50) NULL,
	[AwayFinishingPitcher] [nvarchar](50) NULL,
	[HomeFinishingPitcher] [nvarchar](50) NULL
) ON [PRIMARY]

GO


